schema_version = "1.0.0"
id = "rykeshrk_batch_render"
version = "0.1.4"
name = "RykeShrk's Batch Render Tool"
tagline = "Render segments from your scene to separate folders for editing"
maintainer = "Jose_Varela <jose@josevarela.net>"
type = "add-on"

website = "https://github.com/JoseVarelaP/ryke-batchrendertool/"
tags = ["Animation", "Render"]

blender_version_min = "4.1.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2024 RykeShrk/Jose_Varela",
]